modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="biomes_beyond"
version="1.0.0"
displayName="biomes beyond"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Lila2048 & yayeverest"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.biomes_beyond]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration